county-name: test_county
county-path: C:\Users\Nick\Documents\code\ga-tax-assessment\tests\test_files_dir
var-map-path: ../input/var_maps/test_map.csv
operations:
  m1:
    type: merge
    files:
      DIGEST:
  a1:
    type: append
    files:
      m1
      CMR
output:
  path: test-output
  formats:
    - csv

