county-name: fulton
county-path: ../data/fulton
var-map-path: ../input/var_maps/fulton_map.csv
operations:
  append1:
    type: append
    files:
      DIGEST:
      NF:
      SF:
output:
  path: test-output
  formats:
    - parquet
    - csv

